### ISSUE TITLE
Farming website improvements

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#108]
We are getting incredible traction for farming. 
Website calls for improved content and user flow making sure we give the best overview of what we have and quickest way to participate.

- [x] clean up the repo: https://github.com/threefoldfoundation/www_threefold_farming/issues/105 (@samaradel )
- [x] improve content/user flow: https://github.com/threefoldfoundation/www_threefold_farming/issues/106 (@Sacha96 )
- [x] apply suggested improvements: https://github.com/threefoldfoundation/www_threefold_farming/issues/107 (@Vilnite )
- [x] get stakeholders approval on staging
- [x] push live on production

**Comment by Vilnite** [comment]
See if this can be used anywhere:

<img width="1001" alt="Screenshot 2021-06-04 at 16 58 57" src="https://user-images.githubusercontent.com/20182572/120829263-420aa380-c56e-11eb-9fec-282d8395ba73.png">

<img width="905" alt="Screenshot 2021-06-04 at 17 01 22" src="https://user-images.githubusercontent.com/20182572/120829273-45059400-c56e-11eb-9ba1-d871cd7eefd9.png">
